from tkinter import *
from tkinter import ttk

T = Tk()
T.maxsize(260, 130)
T.minsize(260, 130)
T.title('后台管理-添加用户')
New_Add = Frame(T)
info_1 = Label(New_Add, text='用户名')
info_2 = Label(New_Add, text='输入密码')
info_3 = Label(New_Add, text='重复密码')
username = StringVar()
first_password = StringVar()
second_password = StringVar()
name = ttk.Entry(New_Add, textvariable=username)
password_1 = ttk.Entry(New_Add, textvariable=first_password)
password_2 = ttk.Entry(New_Add, textvariable=second_password)
Radio_zone = IntVar()
Radio_1 = ttk.Radiobutton(New_Add, text='普通用户', variable=Radio_zone, value=0)
Radio_2 = ttk.Radiobutton(New_Add, text='管理用户', variable=Radio_zone, value=1)
# Radio_zone.set(0)
Creat = ttk.Button(New_Add, text='创建')
info_1.grid(row=0, column=0)
info_2.grid(row=1, column=0)
info_3.grid(row=2, column=0)
name.grid(row=0, column=1)
password_1.grid(row=1, column=1)
password_2.grid(row=2, column=1)
Radio_1.grid(row=3, column=0)
Radio_2.grid(row=3, column=1)
Creat.grid(row=4, column=0)
New_Add.grid(padx=20)
T.mainloop()